name: Update README

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '20 22 * * *'  # Runs every day at 10:20 PM UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.17.1'
      - name: Install Dependencies
        run: npm install
      - name: Fetch Quote and Update README
        run: node update-readme.js
